Merged PR 12856: Add missing project dependencies so mono repo wide builds work
Added missing project dependencies to the AWS.TransferProxy and MasterData.Repository solutions.

Without them builds were failing with the likes of the following:

`IProjectRepository.cs(14,10): error CS0246: The type or namespace name 'ImportedFile' could not be found (are you missing a using directive or an assembly reference?) [/build/src/Common/MasterDataRepositories/src/VSS.MasterData.Repositories.csproj]`

Related work items: #81178